# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XybaH3FlZiCYa_SoUWtVymEFZM7eEjxw
"""

!pip install opencv-python matplotlib
import cv2
import matplotlib.pyplot as plt