# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XW4pPvvmUROah78Fi15r38hDnfLikuQd
"""

import cv2
from google.colab import files
uploaded = files.upload()
img = cv2.imread(list(uploaded.keys())[0])   #Load image
img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

import matplotlib.pyplot as plt
plt.imshow(img)
plt.axis('off')
plt.show()

cropped = img[100:400, 200:500]
rotated = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
plt.figure(figsize=(10,5))
plt.subplot(1,2,1); plt.imshow(img); plt.title('Original'); plt.axis('off')
plt.subplot(1,2,2); plt.imshow(rotated); plt.title("Rotated"); plt.axis('off')
plt.show()

gray = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
edges = cv2.Canny(gray, 100, 200)
plt.imshow(edges, cmap='gray')
plt.title("Edges Detected !")
plt.show()